twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        pathArticleAttachment: '%upload%'
        link_fb: '%fb%'
        email: '%email.address%'

when@test:
    twig:
        strict_variables: true
